kind = "mobile"
previewPath = "/kwanzavisa-mobile/"
title = "KwanzaVisa Mobile"
version = "1.0.0"
id = "artifacts/kwanzavisa-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/kwanzavisa-mobile/" ]
localPort = 21084

[services.development]
run = "pnpm --filter @workspace/kwanzavisa-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kwanzavisa-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/kwanzavisa-mobile", "run", "serve" ]

[services.env]
PORT = "21084"
BASE_PATH = "/kwanzavisa-mobile/"
